### PR TITLE
feat(hackathon): automated email setup

### PR DESCRIPTION
**Pull request by cloverzer0**
### An automated email subscription system. 
The core functionality is implemented using AWS SES (Simple Email Service) and provides an API endpoint for subscribing to a newsletter.

1. AWS SES Configuration: Configured AWS SES with credentials and region settings sourced from environment variables.
2. subscribeToNewsletterRouter: Added a new TRPC procedure to handle newsletter subscriptions. This procedure:

Please review the changes and let me know if there are any adjustments or additional tests required.

### CODE REVIEW

**Comment by JeremyFriesenGitHub** [comment]
i haven't looked really into the code yet, but I'm wondering if the application form procedure commit in this PR should be in your [other PR](https://github.com/cuhacking/2025/pull/86) for the application form procedure?

**Comment by cloverzer0** [comment]
> i haven't looked really into the code yet, but I'm wondering if the application form procedure commit in this PR should be in your [other PR](https://github.com/cuhacking/2025/pull/86) for the application form procedure?

I made a branch from the first PR, thought it would be better to do that to be able to look at just one PR, this one.

**Comment by HasithDeAlwis** [comment]
@cloverzer0 we have to start phasing out the /hackathon directory, let's focus on getting this ready to be merged in the correct way. What is your availability this weekend to talk about this, let's prioritize this BEFORE we do anything more with the webhooks

**Comment by MFarabi619** [comment]
Is the development team budget finalized? What are our estimates for how much this is going to cost for testing and prod?

**Comment by MFarabi619** [comment]
Closing as stale

**Pull request closed without merging**
