### PR TITLE
chore: consolidate-marketing-site-hacker-portal-app-and-docs-site-into-monorepo

### PR DESCRIPTION
**Pull request by MFarabi619**
Continuation of work on #40, previous PR was #60.

For reviewers, this PR contains repo-wide lints, and can instead be reviewed commit-by-commit.

### Key Changes
✅ Completed migration of Husky, Commitlint, and Commitizen
- Updated Commitizen CLI for new monorepo architecture
    - Improved conventional spec types descriptions 
image
    - Updated scopes with multi-select feature
image
    - Removed "Does this affect any open issues?" question
image

- Updated docs with improved spec
    - Changed project scope separator from `+` to `,`
        - Easier to press on the keyboard than `+`
      
image

NOTE: Picking multiple scopes in the CLI does not correspond to the spec defined in the updated docs :(
No worries since it doesn't break the semver bot.

✅ Fixed broken pipelines by reverting them to use `pnpm` instead of `bun`, and use `nx` for build/test commands.
✅ Merged ESLint base rules with `docs-e2e`, `web-e2e`, and `portal-e2e`, and added legacy `hackathon` and `landing-page` projects to be ignored
✅ Linted all projects in the monorepo except `hackathon` and `landing-page`
✅ Fixed broken E2E tests for docs site in `docs-e2e` and `hackathon`

image

### CODE REVIEW

**Comment by MFarabi619** [comment]
Works locally, absolutely no idea why it's failing in the pipeline

image

**Review by HasithDeAlwis — APPROVED** [review]
Any particular reason for removing the "Does this effect any open PRs?" I thought we wanted to have issues linked with each commit? Looks amazing tho, good work on this 👍

**Comment by MFarabi619** [comment]
> Any particular reason for removing the "Does this effect any open PRs?" I thought we wanted to have issues linked with each commit? Looks amazing tho, good work on this 👍

Yeah just removed the 
>Does this affect any open issues?

question because we currently don't have linting & automation set up for it, and any mishaps could cause major confusion in the future. It's on my list of things to look into though and definitely something we can do. Having to constantly hit a blank enter on that question was annoying and would've confused contributors.

This is a case where trunk-based dev comes to the rescue since we're working with short-lived branches with a naming convention. Every branch is already linked to a single issue. In this PR for example you can see I'm working off the same branch I was before, and it's still linked to the same issue.

But yes we can't trace each individual commit to the issue just with a quick glance until we implement the numbering thing. I'm pretty confident that can be automated completely, and in one go we can also automate the rest of the PR and issue templates too.

**Comment by MFarabi619** [comment]
Yeah I'll dig it up somehow. At least at it works locally and every commit is linted automatically by `lint-staged`.

**Pull request merged**
